project_id = "oczkinultzflofespdog"

[functions.tts-account1]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.upload-verse-audio]
verify_jwt = false

[functions.tts-account2]
verify_jwt = false
